//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVC_StartProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class KitapTbl
    {
        public int KitapID { get; set; }
        public string Adi { get; set; }
        public string Sayfano { get; set; }
        public string Yazar { get; set; }
        public Nullable<int> Kategori { get; set; }
    
        public virtual KategoriTbl KategoriTbl { get; set; }
    }
}
